import os

class Config(object):
    API_ID = os.environ.get("API_ID", "8186557")
    API_HASH = os.environ.get("API_HASH", "efd77b34c69c164ce158037ff5a0d117")
    SESSION_ONE = os.environ.get("SESSION_ONE", "1AZWarzgBu6zAcvsnYKPu0eXRah7GbB4G9NbhGvrzAZM_fn6XMQYcgxtcIAxsx-PxU_WFHTerr5cI-1KXYK0cocpRVgNyO2J5zjn3aqYLVg8BARlVTfsc23CwyrWuHdfEndDswblqpnsQxpN-wkPKbcOrgO6DQlJcFEHoi068dBxnuSrJF7U0jRScdbKVC5UaRd3xHvN_ADpkiP2grM0BbHnvdKPKchTgpwuI8A12ZJhjSk-On5VCQIaVxuuFEQZBUw7Xu-RKMDFXXGZNhtZFjr-S1x4iKnSyvUARjWh58D1_gWQhJPySKmREzyMLVM_pmblaMYu4WSEgev4gfnF75MHkl5k7Xxw=")
    SESSION_TWO = os.environ.get("SESSION_TWO", None)
    SESSION_THREE = os.environ.get("SESSION_THREE", None)
    SESSION_FOUR = os.environ.get("SESSION_FOUR", None)
    SESSION_FIVE = os.environ.get("SESSION_FIVE", None)
    BOT_TOKEN  = os.environ.get("BOT_TOKEN", "5834621828:AAHhQQa_hmy3iARLtDn3Xilml_0mv1U_HE0")
    BOT_USERNAME  = os.environ.get("BOT_USERNAME", None)
    OWNER_ID = os.environ.get("OWNER_ID", "5274174589")
    OWNER_NAME = os.environ.get("OWNER_NAME", "aaakash")
    OWNER_USERNAME = os.environ.get("OWNER_USERNAME", "wtfaakashxd")
    CO_OWNER_ID = set(int(x) for x in os.environ.get("CO_OWNER_ID", None).split())
    SUDO_USERS = set(int(x) for x in os.environ.get("SUDO_USERS", None).split())
    HEROKU_APP_NAME = os.environ.get("HEROKU_APP_NAME", None)
    HEROKU_API_KEY = os.environ.get("HEROKU_API_KEY", None)
    DISPLAY_PIC = os.environ.get("DISPLAY_PIC", None)
    BIO_MSG = os.environ.get("BIO_MSG", "op gfc")
