# MAFIA SPAM BOT CODE 

from spambot import *
from spambot import MafiaBot1, MafiaBot2, MafiaBot3, MafiaBot4, MafiaBot5
from telethon import events

@MafiaBot1.on(events.NewMessage(incoming=True, pattern='0P'))
@MafiaBot2.on(events.NewMessage(incoming=True, pattern='0P'))
@MafiaBot3.on(events.NewMessage(incoming=True, pattern='0P'))
@MafiaBot4.on(events.NewMessage(incoming=True, pattern='0P'))
@MafiaBot5.on(events.NewMessage(incoming=True, pattern='0P'))
async def oneword(e): 
    if e.sender_id in MY_USERS:
        await e.client.send_message(e.chat_id, "CHAL")
        await e.client.send_message(e.chat_id, "RHA")
        await e.client.send_message(e.chat_id, "TERA")
        await e.client.send_message(e.chat_id, "KEYBOARD")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "SUAR")
        await e.client.send_message(e.chat_id, "CHMAR")
        await e.client.send_message(e.chat_id, "BSDK")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "MAAA")
        await e.client.send_message(e.chat_id, "BHOSDAA")
        await e.client.send_message(e.chat_id, "BEHEN")
        await e.client.send_message(e.chat_id, "KA")
        await e.client.send_message(e.chat_id, "LAWDA")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "AULAAD")
        await e.client.send_message(e.chat_id, "USKI")
        await e.client.send_message(e.chat_id, "MAA")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "CHUT")
        await e.client.send_message(e.chat_id, "BEHNN")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "BHOSDEE")
        await e.client.send_message(e.chat_id, "KOOO")
        await e.client.send_message(e.chat_id, "APNEE")
        await e.client.send_message(e.chat_id, "LUNDD")
        await e.client.send_message(e.chat_id, "SEE")
        await e.client.send_message(e.chat_id, "CHODUA A JAO")
        await e.client.send_message(e.chat_id, "BAHENN")
        await e.client.send_message(e.chat_id, "KEE")
        await e.client.send_message(e.chat_id, "LODOD")
        await e.client.send_message(e.chat_id, "ABB")
        await e.client.send_message(e.chat_id, "KAROO")
        await e.client.send_message(e.chat_id, "SPEED")
        await e.client.send_message(e.chat_id, "BEHEN")
        await e.client.send_message(e.chat_id, "KA")
        await e.client.send_message(e.chat_id, "LWDA")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "AULAAD")
        await e.client.send_message(e.chat_id, "teri")
        await e.client.send_message(e.chat_id, "MAA")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "CHUT ME MERA LODA")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "KYA")
        await e.client.send_message(e.chat_id, "HUA")
        await e.client.send_message(e.chat_id, "BAAP")
        await e.client.send_message(e.chat_id, "KE")
        await e.client.send_message(e.chat_id, "AAGE")
        await e.client.send_message(e.chat_id, "NHI")
        await e.client.send_message(e.chat_id, "CHAL")
        await e.client.send_message(e.chat_id, "RHA")
        await e.client.send_message(e.chat_id, "TER")
        await e.client.send_message(e.chat_id, "KEYBOARD")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "SUAR")
        await e.client.send_message(e.chat_id, "CHMAR")
        await e.client.send_message(e.chat_id, "BSDK")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "MAAA")
        await e.client.send_message(e.chat_id, "BHOSDAA")
        await e.client.send_message(e.chat_id, "CHODUU")
        await e.client.send_message(e.chat_id, "RANDIK")
        await e.client.send_message(e.chat_id, "BEEEJ")
        await e.client.send_message(e.chat_id, "BEHEN")
        await e.client.send_message(e.chat_id, "KEE")
        await e.client.send_message(e.chat_id, "LAUDE")
        await e.client.send_message(e.chat_id, "BEHEN")
        await e.client.send_message(e.chat_id, "LAUDEEEE")
        await e.client.send_message(e.chat_id, "TERIIII")
        await e.client.send_message(e.chat_id, "MAAA")
        await e.client.send_message(e.chat_id, "KOOOO")
        await e.client.send_message(e.chat_id, "CHODUUU")
        await e.client.send_message(e.chat_id, "AB")
        await e.client.send_message(e.chat_id, "MAAAA")
        await e.client.send_message(e.chat_id, "KIIII")
        await e.client.send_message(e.chat_id, "CHUTT")
        await e.client.send_message(e.chat_id, "MERAAA")
        await e.client.send_message(e.chat_id, "MANNN")
        await e.client.send_message(e.chat_id, "BHARGYAAAA")
        await e.client.send_message(e.chat_id, "APNIII")
        await e.client.send_message(e.chat_id, "BEHENNN")
        await e.client.send_message(e.chat_id, "KOOO")
        await e.client.send_message(e.chat_id, "BHEEJJJ ABBB")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "MA")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "BUND")
        await e.client.send_message(e.chat_id, "ME")
        await e.client.send_message(e.chat_id, "SILECER")
        await e.client.send_message(e.chat_id, "DAL")
        await e.client.send_message(e.chat_id, "DUNGA")
        await e.client.send_message(e.chat_id, "XD")
        await e.client.send_message(e.chat_id, "KALPTA")
        await e.client.send_message(e.chat_id, "REH")
        await e.client.send_message(e.chat_id, "BETA")
        await e.client.send_message(e.chat_id, "HU")
        await e.client.send_message(e.chat_id, "TU")
        await e.client.send_message(e.chat_id, "ISSI LAYAK")
        await e.client.send_message(e.chat_id, "HAI")
        await e.client.send_message(e.chat_id, "CHAKKE")
        await e.client.send_message(e.chat_id, "XD")
        await e.client.send_message(e.chat_id, "AJA BHEN KE")
        await e.client.send_message(e.chat_id, "LUND")
        await e.client.send_message(e.chat_id, "PYTHON")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "SKRIPT")
        await e.client.send_message(e.chat_id, "BANAKE")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "MA")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "CHUT")
        await e.client.send_message(e.chat_id, "ME")
        await e.client.send_message(e.chat_id, "DAL")
        await e.client.send_message(e.chat_id, "DU ")
        await e.client.send_message(e.chat_id, "BSDK")
        await e.client.send_message(e.chat_id, "NILAM KRDU")
        await e.client.send_message(e.chat_id, "BEHENN KE LUNDD")
        await e.client.send_message(e.chat_id, "GAWARR")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "TERII")
        await e.client.send_message(e.chat_id, "MUJRAA")
        await e.client.send_message(e.chat_id, "WALIII")
        await e.client.send_message(e.chat_id, "AMMMA KO")
        await e.client.send_message(e.chat_id, "TERI MA KA")
        await e.client.send_message(e.chat_id, "GANG RAPE")
        await e.client.send_message(e.chat_id, "TEREE")
        await e.client.send_message(e.chat_id, "VAISHYAA")
        await e.client.send_message(e.chat_id, "BEHENN KEEE")
        await e.client.send_message(e.chat_id, "PAR APNA")
        await e.client.send_message(e.chat_id, "LAUDA")
        await e.client.send_message(e.chat_id, "PREGNENNT KRUU")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "MAA")
        await e.client.send_message(e.chat_id, "KI")
        await e.client.send_message(e.chat_id, "CHUT")
        await e.client.send_message(e.chat_id, "SUAR")
        await e.client.send_message(e.chat_id, "LDKE")
        await e.client.send_message(e.chat_id, "BEHENCHOD")
        await e.client.send_message(e.chat_id, "AJA BAAP")
        await e.client.send_message(e.chat_id, "KI SPEED")
        await e.client.send_message(e.chat_id, "MATCH")
        await e.client.send_message(e.chat_id, "KRLE")
        await e.client.send_message(e.chat_id, "CHUTKE")
        await e.client.send_message(e.chat_id, "CHINNAL")
        await e.client.send_message(e.chat_id, "MADARXHOD")
        await e.client.send_message(e.chat_id, "KE PILLE")
        await e.client.send_message(e.chat_id, "BAAP KI")
        await e.client.send_message(e.chat_id, "SPEED DEKH")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "1 WORD")
        await e.client.send_message(e.chat_id, "KREGA")
        await e.client.send_message(e.chat_id, "RANDI KE")
        await e.client.send_message(e.chat_id, "SUWaR")
        await e.client.send_message(e.chat_id, "KA BACCHA")
        await e.client.send_message(e.chat_id, "HAI TU")
        await e.client.send_message(e.chat_id, "MAA")
        await e.client.send_message(e.chat_id, "BHAGNA")
        await e.client.send_message(e.chat_id, "AB ME")
        await e.client.send_message(e.chat_id, "TERI MAA KI")
        await e.client.send_message(e.chat_id, "CHUT MARUGA")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "LDKEE")
        await e.client.send_message(e.chat_id, "KAISI HAI")
        await e.client.send_message(e.chat_id, "TERE BAAP KI SPEED")
        await e.client.send_message(e.chat_id, "HAYE HAYE HAYE")
        await e.client.send_message(e.chat_id, "KYA HI")
        await e.client.send_message(e.chat_id, "CHUDA HAI TU")
        await e.client.send_message(e.chat_id, "HAYE HAYE MAJEEE")
        await e.client.send_message(e.chat_id, "MAA")
        await e.client.send_message(e.chat_id, "CHOD")
        await e.client.send_message(e.chat_id, "DII MENE")
        await e.client.send_message(e.chat_id, "Hᴜʜ")
        await e.client.send_message(e.chat_id, "CHALLL")
        await e.client.send_message(e.chat_id, "BACHE")
        await e.client.send_message(e.chat_id, "TERII")
        await e.client.send_message(e.chat_id, "BEHENNNN")
        await e.client.send_message(e.chat_id, "KAA RAPEE")
        await e.client.send_message(e.chat_id, "KRUU")
        await e.client.send_message(e.chat_id, "TERIII")
        await e.client.send_message(e.chat_id, "MAA KOO")
        await e.client.send_message(e.chat_id, "NILAM KRDU")
        await e.client.send_message(e.chat_id, "BEHENN KE LUNDD")
        await e.client.send_message(e.chat_id, "SUWARR")
        await e.client.send_message(e.chat_id, "GAWARR")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "CHODEEE")
        await e.client.send_message(e.chat_id, "TERII")
        await e.client.send_message(e.chat_id, "MUJRAA")
        await e.client.send_message(e.chat_id, "KREE")
        await e.client.send_message(e.chat_id, "WALIII")
        await e.client.send_message(e.chat_id, "CHODUUUU")
        await e.client.send_message(e.chat_id, "TERII")
        await e.client.send_message(e.chat_id, "MAKAAA")
        await e.client.send_message(e.chat_id, "GANG RAPE")
        await e.client.send_message(e.chat_id, "KARDUGAA")
        await e.client.send_message(e.chat_id, "TEREE")
        await e.client.send_message(e.chat_id, "VAISHYAA")
        await e.client.send_message(e.chat_id, "BEHENN KEEE")
        await e.client.send_message(e.chat_id, "GANDEE BHOSDEE")
        await e.client.send_message(e.chat_id, "PAR APNA")
        await e.client.send_message(e.chat_id, "RAKH KE")
        await e.client.send_message(e.chat_id, "PREGNENNT KRUU")
        await e.client.send_message(e.chat_id, "GFC")
        await e.client.send_message(e.chat_id, "TERAA")
        await e.client.send_message(e.chat_id, "BAAAP")
        await e.client.send_message(e.chat_id, "HAIIII")
        await e.client.send_message(e.chat_id, "SMJHAA BSDKK")
        await e.client.send_message(e.chat_id, "TOR")
        await e.client.send_message(e.chat_id, "bUR")
        await e.client.send_message(e.chat_id, "CHODA")
        await e.client.send_message(e.chat_id, "RANDIII")
        await e.client.send_message(e.chat_id, "KEEEE")
        await e.client.send_message(e.chat_id, "BEEEJ")
        await e.client.send_message(e.chat_id, "KEE")
        await e.client.send_message(e.chat_id, "BHOSDEE")
        await e.client.send_message(e.chat_id, "TERIII")
        await e.client.send_message(e.chat_id, "MAA NAA")
        await e.client.send_message(e.chat_id, "MARJAYEE")
        await e.client.send_message(e.chat_id, "CHOD")
        await e.client.send_message(e.chat_id, "TERRII")
        await e.client.send_message(e.chat_id, "MA")
        await e.client.send_message(e.chat_id, "KOO")
        await e.client.send_message(e.chat_id, "NILAM KRDUGA")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "KOOO")
        await e.client.send_message(e.chat_id, "CHODUU")
        await e.client.send_message(e.chat_id, "TERI")
        await e.client.send_message(e.chat_id, "MAAA")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "BHOSDE")
        await e.client.send_message(e.chat_id, "KA")
        await e.client.send_message(e.chat_id, "GULAB")
        await e.client.send_message(e.chat_id, "JAMUN")
        await e.client.send_message(e.chat_id, "BANA")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "KUTTO")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "MUH")
        await e.client.send_message(e.chat_id, "MEE")
        await e.client.send_message(e.chat_id, "DAL")
        await e.client.send_message(e.chat_id, "DUNGA")
        await e.client.send_message(e.chat_id, "BAHEN")
        await e.client.send_message(e.chat_id, "KEEE")
        await e.client.send_message(e.chat_id, "LUND")
        await e.client.send_message(e.chat_id, "SALE")
        await e.client.send_message(e.chat_id, "EEK")
        await e.client.send_message(e.chat_id, "RAPTE")
        await e.client.send_message(e.chat_id, "MEE")
        await e.client.send_message(e.chat_id, "TERA")
        await e.client.send_message(e.chat_id, "BAAP")
        await e.client.send_message(e.chat_id, "YAANI")
        await e.client.send_message(e.chat_id, "MERA")
        await e.client.send_message(e.chat_id, "LUND")
        await e.client.send_message(e.chat_id, "CHAHTTA")
        await e.client.send_message(e.chat_id, "PHIREGA")
        await e.client.send_message(e.chat_id, "MADAR")
        await e.client.send_message(e.chat_id, "CHOD")
        await e.client.send_message(e.chat_id, "MERA")
        await e.client.send_message(e.chat_id, "LUND")
        await e.client.send_message(e.chat_id, "YAHA")
        await e.client.send_message(e.chat_id, "SEE")
        await e.client.send_message(e.chat_id, "FEK")
        await e.client.send_message(e.chat_id, "KAR")
        await e.client.send_message(e.chat_id, "MARUNGA")
        await e.client.send_message(e.chat_id, "TERE")
        await e.client.send_message(e.chat_id, "MUH")
        await e.client.send_message(e.chat_id, "PAR")
        await e.client.send_message(e.chat_id, "MADAR")
        await e.client.send_message(e.chat_id, "CHOD")
        await e.client.send_message(e.chat_id, "RANDI")
        await e.client.send_message(e.chat_id, "KEEEE")
        await e.client.send_message(e.chat_id, "BACHE")
        await e.client.send_message(e.chat_id, "PAPA")
        await e.client.send_message(e.chat_id, "HAI")
        await e.client.send_message(e.chat_id, "HAM")
        await e.client.send_message(e.chat_id, "TERE")
        await e.client.send_message(e.chat_id, "BAAP")
        await e.client.send_message(e.chat_id, "SEE")
        await e.client.send_message(e.chat_id, "BAKCHODI")
        await e.client.send_message(e.chat_id, "KARNE")
        await e.client.send_message(e.chat_id, "AAYEGA")
        await e.client.send_message(e.chat_id, "TOO")
        await e.client.send_message(e.chat_id, "GAND")
        await e.client.send_message(e.chat_id, "MEE")
        await e.client.send_message(e.chat_id, "SARIYA")
        await e.client.send_message(e.chat_id, "DAL")
        await e.client.send_message(e.chat_id, "DUNGA")
        await e.client.send_message(e.chat_id, "BETE")

